package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;

import fr.umlv.smoreau.beontime.model.TypeUnvailability;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Indisponibilite table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Indisponibilite"
 */
public abstract class BaseUnavailability  implements Serializable {

	public static String PROP_ID_INDISPONIBILITE = "IdIndisponibilite";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_DATE_DEBUT = "DateDebut";
	public static String PROP_ID_TYPE_INDISPONIBILITE = "IdTypeIndisponibilite";
	public static String PROP_DATE_FIN = "DateFin";
	public static String PROP_ID_SUJET_INDISPONIBILITE = "IdSujetIndisponibilite";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idIndisponibilite;

	// fields
	private java.lang.Long _idSujetIndisponibilite;
	private java.lang.String _description;
	private java.util.Date _dateFin;
	private java.util.Date _dateDebut;

	// many to one
	private TypeUnvailability _idTypeIndisponibilite;


	// constructors
	public BaseUnavailability () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUnavailability (java.lang.Long _idIndisponibilite) {
		this.setIdIndisponibilite(_idIndisponibilite);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseUnavailability (
		java.lang.Long _idIndisponibilite,
		TypeUnvailability _idTypeIndisponibilite,
		java.lang.Long _idSujetIndisponibilite) {

		this.setIdIndisponibilite(_idIndisponibilite);
		this.setIdTypeUnvailability(_idTypeIndisponibilite);
		this.setIdSujetIndisponibilite(_idSujetIndisponibilite);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_indisponibilite"
     */
	public java.lang.Long getIdIndisponibilite () {
		return _idIndisponibilite;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idIndisponibilite the new ID
	 */
	public void setIdIndisponibilite (java.lang.Long _idIndisponibilite) {
		this._idIndisponibilite = _idIndisponibilite;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: ID_sujet_indisponibilite
	 */
	public java.lang.Long getIdSujetIndisponibilite () {
		return _idSujetIndisponibilite;
	}

	/**
	 * Set the value related to the column: ID_sujet_indisponibilite
	 * @param _idSujetIndisponibilite the ID_sujet_indisponibilite value
	 */
	public void setIdSujetIndisponibilite (java.lang.Long _idSujetIndisponibilite) {
		this._idSujetIndisponibilite = _idSujetIndisponibilite;
	}


	/**
	 * Return the value associated with the column: Description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: Description
	 * @param _description the Description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: Date_fin
	 */
	public java.util.Date getDateFin () {
		return _dateFin;
	}

	/**
	 * Set the value related to the column: Date_fin
	 * @param _dateFin the Date_fin value
	 */
	public void setDateFin (java.util.Date _dateFin) {
		this._dateFin = _dateFin;
	}


	/**
	 * Return the value associated with the column: Date_debut
	 */
	public java.util.Date getDateDebut () {
		return _dateDebut;
	}

	/**
	 * Set the value related to the column: Date_debut
	 * @param _dateDebut the Date_debut value
	 */
	public void setDateDebut (java.util.Date _dateDebut) {
		this._dateDebut = _dateDebut;
	}


	/**
     * @hibernate.property
     *  column=ID_type_indisponibilite
	 * not-null=true
	 */
	public TypeUnvailability getIdTypeUnvailability () {
		return this._idTypeIndisponibilite;
	}

	/**
	 * Set the value related to the column: ID_type_indisponibilite
	 * @param _idTypeIndisponibilite the ID_type_indisponibilite value
	 */
	public void setIdTypeUnvailability (TypeUnvailability _idTypeIndisponibilite) {
		this._idTypeIndisponibilite = _idTypeIndisponibilite;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseUnavailability)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseUnavailability mObj = (fr.umlv.smoreau.beontime.model.base.BaseUnavailability) obj;
			if (null == this.getIdIndisponibilite() || null == mObj.getIdIndisponibilite()) return false;
			else return (this.getIdIndisponibilite().equals(mObj.getIdIndisponibilite()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdIndisponibilite()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdIndisponibilite().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}