package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Type_cours table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Type_cours"
 */
public abstract class BaseCourseType  implements Serializable {

	public static String PROP_NOM_TYPE_COURS = "NameCourseType";
	public static String PROP_ID_TYPE_COURS = "IdCourseType";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idCourseType;

	// fields
	private java.lang.String _nameCourseType;

	// collections
	private java.util.Set _courses;


	// constructors
	public BaseCourseType () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCourseType (java.lang.Long _idCourseType) {
		this.setIdCourseType(_idCourseType);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_type_cours"
     */
	public java.lang.Long getIdCourseType () {
		return _idCourseType;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idCourseType the new ID
	 */
	public void setIdCourseType (java.lang.Long _idCourseType) {
		this._idCourseType = _idCourseType;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom_type_cours
	 */
	public java.lang.String getNameCourseType () {
		return _nameCourseType;
	}

	/**
	 * Set the value related to the column: Nom_type_cours
	 * @param _nameCourseType the Nom_type_cours value
	 */
	public void setNameCourseType (java.lang.String _nameCourseType) {
		this._nameCourseType = _nameCourseType;
	}


	/**
	 * Return the value associated with the column: CoursSet
	 */
	public java.util.Set getCourses () {
		return this._courses;
	}

	/**
	 * Set the value related to the column: CoursSet
	 * @param _courses the CoursSet value
	 */
	public void setCourses (java.util.Set _courses) {
		this._courses = _courses;
	}
	
	public void addCourse (Object obj) {
		if (null == this._courses) this._courses = new java.util.HashSet();
		this._courses.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseCourseType)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseCourseType mObj = (fr.umlv.smoreau.beontime.model.base.BaseCourseType) obj;
			if (null == this.getIdCourseType() || null == mObj.getIdCourseType()) return false;
			else return (this.getIdCourseType().equals(mObj.getIdCourseType()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdCourseType()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdCourseType().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}