package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Personne table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Personne"
 */
public abstract class BaseUser  implements Serializable {

	public static String PROP_E_MAIL = "EMail";
	public static String PROP_NOM = "Name";
	public static String PROP_NOM_BUREAU = "OfficeName";
	public static String PROP_TELEPHONE = "Telephone";
	public static String PROP_PRENOM = "FirstName";
	public static String PROP_ID_PERSONNE = "IdUser";
	public static String PROP_NOM_BATIMENT_BUREAU = "BuildingNameForOffice";
	public static String PROP_TYPE_PERSONNE = "UserType";
	public static String PROP_LOGIN = "Login";
	public static String PROP_PASSWORD = "Password";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idUser;

	// fields
	private java.lang.String _name;
	private java.lang.String _telephone;
	private java.lang.String _firstName;
	private java.lang.String _officeName;
	private java.lang.String _buildingNameForOffice;
	private java.lang.String _eMail;
	private java.lang.String _userType;
	private java.lang.String _login;
	private java.lang.String _password;

	// collections
	private java.util.Set _formationsResponsible;
	private java.util.Set _formationsInCharge;
	private java.util.Set _subjectsResponsible;
	private java.util.Set _coursesDirected;


	// constructors
	public BaseUser () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUser (java.lang.Long _idUser) {
		this.setIdUser(_idUser);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseUser (
		java.lang.Long _idUser,
		java.lang.String _userType) {

		this.setIdUser(_idUser);
		this.setUserType(_userType);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_personne"
     */
	public java.lang.Long getIdUser () {
		return _idUser;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idUser the new ID
	 */
	public void setIdUser (java.lang.Long _idUser) {
		this._idUser = _idUser;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _name the Nom value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: Telephone
	 */
	public java.lang.String getTelephone () {
		return _telephone;
	}

	/**
	 * Set the value related to the column: Telephone
	 * @param _telephone the Telephone value
	 */
	public void setTelephone (java.lang.String _telephone) {
		this._telephone = _telephone;
	}


	/**
	 * Return the value associated with the column: Prenom
	 */
	public java.lang.String getFirstName () {
		return _firstName;
	}

	/**
	 * Set the value related to the column: Prenom
	 * @param _firstName the Prenom value
	 */
	public void setFirstName (java.lang.String _firstName) {
		this._firstName = _firstName;
	}


	/**
	 * Return the value associated with the column: Nom_bureau
	 */
	public java.lang.String getOfficeName () {
		return _officeName;
	}

	/**
	 * Set the value related to the column: Nom_bureau
	 * @param _officeName the Nom_bureau value
	 */
	public void setOfficeName (java.lang.String _officeName) {
		this._officeName = _officeName;
	}


	/**
	 * Return the value associated with the column: Nom_batiment_bureau
	 */
	public java.lang.String getBuildingNameForOffice () {
		return _buildingNameForOffice;
	}

	/**
	 * Set the value related to the column: Nom_batiment_bureau
	 * @param _buildingNameForOffice the Nom_batiment_bureau value
	 */
	public void setBuildingNameForOffice (java.lang.String _buildingNameForOffice) {
		this._buildingNameForOffice = _buildingNameForOffice;
	}


	/**
	 * Return the value associated with the column: E_mail
	 */
	public java.lang.String getEMail () {
		return _eMail;
	}

	/**
	 * Set the value related to the column: E_mail
	 * @param _eMail the E_mail value
	 */
	public void setEMail (java.lang.String _eMail) {
		this._eMail = _eMail;
	}


	/**
	 * Return the value associated with the column: type_personne
	 */
	public java.lang.String getUserType () {
		return _userType;
	}

	/**
	 * Set the value related to the column: type_personne
	 * @param _userType the type_personne value
	 */
	public void setUserType (java.lang.String _userType) {
		this._userType = _userType;
	}
	
	/**
	 * Return the value associated with the column: login
	 */
	public java.lang.String getLogin () {
		return _login;
	}

	/**
	 * Set the value related to the column: login
	 * @param _login the login value
	 */
	public void setLogin (java.lang.String _login) {
		this._login = _login;
	}
	
	/**
	 * Return the value associated with the column: password
	 */
	public java.lang.String getPassword () {
		return _password;
	}

	/**
	 * Set the value related to the column: password
	 * @param _password the password value
	 */
	public void setPassword (java.lang.String _password) {
		this._password = _password;
	}



	/**
	 * Return the value associated with the column: FormationSetByIdEnseignant
	 */
	public java.util.Set getFormationsResponsible () {
		return this._formationsResponsible;
	}

	/**
	 * Set the value related to the column: FormationSetByIdEnseignant
	 * @param _formationsResponsible the FormationSetByIdEnseignant value
	 */
	public void setFormationsResponsible (java.util.Set _formationsResponsible) {
		this._formationsResponsible = _formationsResponsible;
	}

	public void addFormationResponsible (Object obj) {
		if (null == this._formationsResponsible) this._formationsResponsible = new java.util.HashSet();
		this._formationsResponsible.add(obj);
	}



	/**
	 * Return the value associated with the column: FormationSetByIdSecretaire
	 */
	public java.util.Set getFormationsInCharge () {
		return this._formationsInCharge;
	}

	/**
	 * Set the value related to the column: FormationSetByIdSecretaire
	 * @param _formationsInCharge the FormationSetByIdSecretaire value
	 */
	public void setFormationsInCharge (java.util.Set _formationsInCharge) {
		this._formationsInCharge = _formationsInCharge;
	}
	
	public void addFormationInCharge (Object obj) {
		if (null == this._formationsInCharge) this._formationsInCharge = new java.util.HashSet();
		this._formationsInCharge.add(obj);
	}



	/**
	 * Return the value associated with the column: MatiereSet
	 */
	public java.util.Set getSubjectsResponsible () {
		return this._subjectsResponsible;
	}

	/**
	 * Set the value related to the column: MatiereSet
	 * @param _subjectsResponsible the MatiereSet value
	 */
	public void setSubjectsResponsible (java.util.Set _subjectsResponsible) {
		this._subjectsResponsible = _subjectsResponsible;
	}

	public void addSubjectResponsible (Object obj) {
		if (null == this._subjectsResponsible) this._subjectsResponsible = new java.util.HashSet();
		this._subjectsResponsible.add(obj);
	}



	/**
	 * Return the value associated with the column: CoursSet
	 */
	public java.util.Set getCoursesDirected () {
		return this._coursesDirected;
	}

	/**
	 * Set the value related to the column: CoursSet
	 * @param _coursSet the CoursSet value
	 */
	public void setCoursesDirected (java.util.Set _coursSet) {
		this._coursesDirected = _coursSet;
	}

	public void addCourseDirected (Object obj) {
		if (null == this._coursesDirected) this._coursesDirected = new java.util.HashSet();
		this._coursesDirected.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseUser)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseUser mObj = (fr.umlv.smoreau.beontime.model.base.BaseUser) obj;
			if (null == this.getIdUser() || null == mObj.getIdUser()) return false;
			else return (this.getIdUser().equals(mObj.getIdUser()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdUser()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdUser().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}