package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Type_cours table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Type_cours"
 */
public abstract class BaseTypeCourse  implements Serializable {

	public static String PROP_NOM_TYPE_COURS = "NomTypeCours";
	public static String PROP_ID_TYPE_COURS = "IdTypeCours";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idTypeCours;

	// fields
	private java.lang.String _nomTypeCours;

	// collections
	private java.util.Set _coursSet;


	// constructors
	public BaseTypeCourse () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTypeCourse (java.lang.Long _idTypeCours) {
		this.setIdTypeCours(_idTypeCours);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_type_cours"
     */
	public java.lang.Long getIdTypeCours () {
		return _idTypeCours;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idTypeCours the new ID
	 */
	public void setIdTypeCours (java.lang.Long _idTypeCours) {
		this._idTypeCours = _idTypeCours;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom_type_cours
	 */
	public java.lang.String getNomTypeCours () {
		return _nomTypeCours;
	}

	/**
	 * Set the value related to the column: Nom_type_cours
	 * @param _nomTypeCours the Nom_type_cours value
	 */
	public void setNomTypeCours (java.lang.String _nomTypeCours) {
		this._nomTypeCours = _nomTypeCours;
	}


	/**
	 * Return the value associated with the column: CoursSet
	 */
	public java.util.Set getCoursSet () {
		return this._coursSet;
	}

	/**
	 * Set the value related to the column: CoursSet
	 * @param _coursSet the CoursSet value
	 */
	public void setCoursSet (java.util.Set _coursSet) {
		this._coursSet = _coursSet;
	}
	
	public void addToCoursSet (Object obj) {
		if (null == this._coursSet) this._coursSet = new java.util.HashSet();
		this._coursSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseTypeCourse)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseTypeCourse mObj = (fr.umlv.smoreau.beontime.model.base.BaseTypeCourse) obj;
			if (null == this.getIdTypeCours() || null == mObj.getIdTypeCours()) return false;
			else return (this.getIdTypeCours().equals(mObj.getIdTypeCours()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdTypeCours()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdTypeCours().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}