package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;

import fr.umlv.smoreau.beontime.model.UnavailabilityType;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Indisponibilite table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Indisponibilite"
 */
public abstract class BaseUnavailability  implements Serializable {

	public static String PROP_ID_INDISPONIBILITE = "IdUnavailability";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_DATE_DEBUT = "BeginDate";
	public static String PROP_ID_TYPE_INDISPONIBILITE = "IdUnavailabilityType";
	public static String PROP_DATE_FIN = "EndDate";
	public static String PROP_ID_SUJET_INDISPONIBILITE = "IdUnavailabilitySubject";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idUnavailability;

	// fields
	private java.lang.Long _idUnavailabilitySubject;
	private java.lang.String _description;
	private java.util.Date _endDate;
	private java.util.Date _beginDate;

	// many to one
	private UnavailabilityType _idUnavailabilityType;


	// constructors
	public BaseUnavailability () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUnavailability (java.lang.Long _idUnavailability) {
		this.setIdUnavailability(_idUnavailability);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseUnavailability (
		java.lang.Long _idUnavailability,
		UnavailabilityType _idUnavailabilityType,
		java.lang.Long _idUnavailabilitySubject) {

		this.setIdUnavailability(_idUnavailability);
		this.setIdUnavailabilityType(_idUnavailabilityType);
		this.setIdUnavailabilitySubject(_idUnavailabilitySubject);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_indisponibilite"
     */
	public java.lang.Long getIdUnavailability () {
		return _idUnavailability;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idUnavailability the new ID
	 */
	public void setIdUnavailability (java.lang.Long _idUnavailability) {
		this._idUnavailability = _idUnavailability;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: ID_sujet_indisponibilite
	 */
	public java.lang.Long getIdUnavailabilitySubject () {
		return _idUnavailabilitySubject;
	}

	/**
	 * Set the value related to the column: ID_sujet_indisponibilite
	 * @param _idUnavailabilitySubject the ID_sujet_indisponibilite value
	 */
	public void setIdUnavailabilitySubject (java.lang.Long _idUnavailabilitySubject) {
		this._idUnavailabilitySubject = _idUnavailabilitySubject;
	}


	/**
	 * Return the value associated with the column: Description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: Description
	 * @param _description the Description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: Date_fin
	 */
	public java.util.Date getEndDate () {
		return _endDate;
	}

	/**
	 * Set the value related to the column: Date_fin
	 * @param _endDate the Date_fin value
	 */
	public void setEndDate (java.util.Date _endDate) {
		this._endDate = _endDate;
	}


	/**
	 * Return the value associated with the column: Date_debut
	 */
	public java.util.Date getBeginDate () {
		return _beginDate;
	}

	/**
	 * Set the value related to the column: Date_debut
	 * @param _beginDate the Date_debut value
	 */
	public void setBeginDate (java.util.Date _beginDate) {
		this._beginDate = _beginDate;
	}


	/**
     * @hibernate.property
     *  column=ID_type_indisponibilite
	 * not-null=true
	 */
	public UnavailabilityType getIdUnavailabilityType () {
		return this._idUnavailabilityType;
	}

	/**
	 * Set the value related to the column: ID_type_indisponibilite
	 * @param _idUnavailabilityType the ID_type_indisponibilite value
	 */
	public void setIdUnavailabilityType (UnavailabilityType _idUnavailabilityType) {
		this._idUnavailabilityType = _idUnavailabilityType;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseUnavailability)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseUnavailability mObj = (fr.umlv.smoreau.beontime.model.base.BaseUnavailability) obj;
			if (null == this.getIdUnavailability() || null == mObj.getIdUnavailability()) return false;
			else return (this.getIdUnavailability().equals(mObj.getIdUnavailability()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdUnavailability()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdUnavailability().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}