package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;

import fr.umlv.smoreau.beontime.model.element.Room;
import fr.umlv.smoreau.beontime.model.timetable.Course;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the A_Lieu_Cours_Local table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="A_Lieu_Cours_Local"
 */
public abstract class BaseTakePlaceCourseRoom  implements Serializable {



	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private Room _idRoom;
	private Course _idCourse;


	// constructors
	public BaseTakePlaceCourseRoom () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTakePlaceCourseRoom (
		Room _idRoom,
		Course _idCourse) {

		this.setIdRoom(_idRoom);
		this.setIdCourse(_idCourse);
		initialize();
	}

	protected void initialize () {}



	/**
     * @hibernate.property
     *  column=ID_local
	 * not-null=true
	 */
	public Room getIdRoom () {
		return this._idRoom;
	}

	/**
	 * Set the value related to the column: ID_local
	 * @param _idRoom the ID_local value
	 */
	public void setIdRoom (Room _idRoom) {
		this._idRoom = _idRoom;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
     * @hibernate.property
     *  column=ID_cours
	 * not-null=true
	 */
	public Course getIdCourse () {
		return this._idCourse;
	}

	/**
	 * Set the value related to the column: ID_cours
	 * @param _idCourse the ID_cours value
	 */
	public void setIdCourse (Course _idCourse) {
		this._idCourse = _idCourse;
		this.hashCode = Integer.MIN_VALUE;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.association.TakePlaceCourseRoom)) return false;
		else {
			fr.umlv.smoreau.beontime.model.association.TakePlaceCourseRoom mObj = (fr.umlv.smoreau.beontime.model.association.TakePlaceCourseRoom) obj;
			if (null != this.getIdRoom() && null != mObj.getIdRoom()) {
				if (!this.getIdRoom().equals(mObj.getIdRoom())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getIdCourse() && null != mObj.getIdCourse()) {
				if (!this.getIdCourse().equals(mObj.getIdCourse())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getIdRoom()) {
				sb.append(this.getIdRoom().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getIdCourse()) {
				sb.append(this.getIdCourse().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}