package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;

import fr.umlv.smoreau.beontime.model.Group;
import fr.umlv.smoreau.beontime.model.user.Person;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the appartient_etudiant_groupe table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="appartient_etudiant_groupe"
 */
public abstract class BaseAppartientEtudiantGroupe implements Serializable {

	public static String PROP_ID_GROUPE = "IdGroupe";
	public static String PROP_ID_ETUDIANT = "IdEtudiant";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private Person _idEtudiant;
	private Group _idGroupe;


	// constructors
	public BaseAppartientEtudiantGroupe () {
		initialize();
	}
	
	/**
	 * Constructor for primary key
	 */
	public BaseAppartientEtudiantGroupe (
		Person _idEtudiant,
		Group _idGroupe) {

		this.setIdEtudiant(_idEtudiant);
		this.setIdGroupe(_idGroupe);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="id_groupe"
     */
	public Group getIdGroupe () {
		return _idGroupe;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idGroupe the new ID
	 */
	public void setIdGroupe (Group _idGroupe) {
		this._idGroupe = _idGroupe;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: id_etudiant
	 */
	public Person getIdEtudiant () {
		return _idEtudiant;
	}

	/**
	 * Set the value related to the column: id_etudiant
	 * @param _idEtudiant the id_etudiant value
	 */
	public void setIdEtudiant (Person _idEtudiant) {
		this._idEtudiant = _idEtudiant;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseAppartientEtudiantGroupe)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseAppartientEtudiantGroupe mObj = (fr.umlv.smoreau.beontime.model.base.BaseAppartientEtudiantGroupe) obj;
			if (null == this.getIdGroupe() || null == mObj.getIdGroupe()) return false;
			else return (this.getIdGroupe().equals(mObj.getIdGroupe()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdGroupe()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdGroupe().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}