package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;

import fr.umlv.smoreau.beontime.model.Group;
import fr.umlv.smoreau.beontime.model.user.User;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the appartient_etudiant_groupe table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="appartient_etudiant_groupe"
 */
public abstract class BaseBelongStudentGroup implements Serializable {

	public static String PROP_ID_GROUPE = "IdGroup";
	public static String PROP_ID_ETUDIANT = "IdStudent";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private User _idStudent;
	private Group _idGroup;


	// constructors
	public BaseBelongStudentGroup () {
		initialize();
	}
	
	/**
	 * Constructor for primary key
	 */
	public BaseBelongStudentGroup (
		User _idStudent,
		Group _idGroup) {

		this.setIdStudent(_idStudent);
		this.setIdGroup(_idGroup);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="id_groupe"
     */
	public Group getIdGroup () {
		return _idGroup;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idGroup the new ID
	 */
	public void setIdGroup (Group _idGroup) {
		this._idGroup = _idGroup;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: id_etudiant
	 */
	public User getIdStudent () {
		return _idStudent;
	}

	/**
	 * Set the value related to the column: id_etudiant
	 * @param _idStudent the id_etudiant value
	 */
	public void setIdStudent (User _idStudent) {
		this._idStudent = _idStudent;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseBelongStudentGroup)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseBelongStudentGroup mObj = (fr.umlv.smoreau.beontime.model.base.BaseBelongStudentGroup) obj;
			if (null == this.getIdGroup() || null == mObj.getIdGroup()) return false;
			else return (this.getIdGroup().equals(mObj.getIdGroup()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdGroup()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdGroup().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}