package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Matiere table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Matiere"
 */
public abstract class BaseSubject  implements Serializable {

	public static String PROP_NB_GROUPE_TP = "NbTpGroups";
	public static String PROP_NB_HEURE_TD = "NbTdHours";
	public static String PROP_ID_MATIERE = "IdSubject";
	public static String PROP_NB_GROUPE_TD = "NbTdGroups";
	public static String PROP_NB_HEURE_MAG = "NbMagHours";
	public static String PROP_NB_HEURE_TP = "NbTpHours";
	public static String PROP_NB_GROUPE_MAG = "NbMagGroups";
	public static String PROP_ID_FORMATION = "IdFormation";
	public static String PROP_ID_ENSEIGNANT = "IdTeacher";
	public static String PROP_INTITULE = "Heading";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idSubject;

	// fields
	private java.lang.Integer _nbTpHours;
	private java.lang.Integer _nbMagHours;
	private java.lang.Integer _nbTdGroups;
	private java.lang.Integer _nbMagGroups;
	private java.lang.Integer _nbTdHours;
	private java.lang.String _heading;
	private java.lang.Integer _nbTpGroups;
	private java.lang.Long _idTeacher;
	private java.lang.Long _idFormation;

	// collections
	private java.util.Set _GroupsSubjectsTakingPart;


	// constructors
	public BaseSubject () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseSubject (java.lang.Long _idSubject) {
		this.setIdSubject(_idSubject);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseSubject (
		java.lang.Long _idSubject,
		java.lang.Long _idTeacher,
		java.lang.Long _idFormation) {

		this.setIdSubject(_idSubject);
		this.setIdTeacher(_idTeacher);
		this.setIdFormation(_idFormation);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_matiere"
     */
	public java.lang.Long getIdSubject () {
		return _idSubject;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idSubject the new ID
	 */
	public void setIdSubject (java.lang.Long _idSubject) {
		this._idSubject = _idSubject;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: NB_heure_TP
	 */
	public java.lang.Integer getNbTpHours () {
		return _nbTpHours;
	}

	/**
	 * Set the value related to the column: NB_heure_TP
	 * @param _nbTpHours the NB_heure_TP value
	 */
	public void setNbTpHours (java.lang.Integer _nbTpHours) {
		this._nbTpHours = _nbTpHours;
	}


	/**
	 * Return the value associated with the column: NB_heure_MAG
	 */
	public java.lang.Integer getNbMagHours () {
		return _nbMagHours;
	}

	/**
	 * Set the value related to the column: NB_heure_MAG
	 * @param _nbMagHours the NB_heure_MAG value
	 */
	public void setNbMagHours (java.lang.Integer _nbMagHours) {
		this._nbMagHours = _nbMagHours;
	}


	/**
	 * Return the value associated with the column: NB_groupe_TD
	 */
	public java.lang.Integer getNbTdGroups () {
		return _nbTdGroups;
	}

	/**
	 * Set the value related to the column: NB_groupe_TD
	 * @param _nbTdGroups the NB_groupe_TD value
	 */
	public void setNbTdGroups (java.lang.Integer _nbTdGroups) {
		this._nbTdGroups = _nbTdGroups;
	}


	/**
	 * Return the value associated with the column: NB_groupe_MAG
	 */
	public java.lang.Integer getNbMagGroups () {
		return _nbMagGroups;
	}

	/**
	 * Set the value related to the column: NB_groupe_MAG
	 * @param _nbMagGroups the NB_groupe_MAG value
	 */
	public void setNbMagGroups (java.lang.Integer _nbMagGroups) {
		this._nbMagGroups = _nbMagGroups;
	}


	/**
	 * Return the value associated with the column: NB_heure_TD
	 */
	public java.lang.Integer getNbTdHours () {
		return _nbTdHours;
	}

	/**
	 * Set the value related to the column: NB_heure_TD
	 * @param _nbTdHours the NB_heure_TD value
	 */
	public void setNbTdHours (java.lang.Integer _nbTdHours) {
		this._nbTdHours = _nbTdHours;
	}


	/**
	 * Return the value associated with the column: Intitule
	 */
	public java.lang.String getHeading () {
		return _heading;
	}

	/**
	 * Set the value related to the column: Intitule
	 * @param _heading the Intitule value
	 */
	public void setHeading (java.lang.String _heading) {
		this._heading = _heading;
	}


	/**
	 * Return the value associated with the column: NB_groupe_TP
	 */
	public java.lang.Integer getNbTpGroups () {
		return _nbTpGroups;
	}

	/**
	 * Set the value related to the column: NB_groupe_TP
	 * @param _nbTpGroups the NB_groupe_TP value
	 */
	public void setNbTpGroups (java.lang.Integer _nbTpGroups) {
		this._nbTpGroups = _nbTpGroups;
	}


	/**
     * @hibernate.property
     *  column=ID_enseignant
	 * not-null=true
	 */
	public java.lang.Long getIdTeacher () {
		return this._idTeacher;
	}

	/**
	 * Set the value related to the column: ID_enseignant
	 * @param _idTeacher the ID_enseignant value
	 */
	public void setIdTeacher (java.lang.Long _idTeacher) {
		this._idTeacher = _idTeacher;
	}


	/**
     * @hibernate.property
     *  column=ID_formation
	 * not-null=true
	 */
	public java.lang.Long getIdFormation () {
		return this._idFormation;
	}

	/**
	 * Set the value related to the column: ID_formation
	 * @param _idFormation the ID_formation value
	 */
	public void setIdFormation (java.lang.Long _idFormation) {
		this._idFormation = _idFormation;
	}


	/**
	 * Return the value associated with the column: ParticipeGroupeMatiereCoursSet
	 * @deprecated
	 */
	public java.util.Set getGroupsCoursesTakingPart () {
		return this._GroupsSubjectsTakingPart;
	}

	/**
	 * Set the value related to the column: ParticipeGroupeMatiereCoursSet
	 * @param _groupsCoursesTakingPart the ParticipeGroupeMatiereCoursSet value
	 * @deprecated
	 */
	public void setGroupsCoursesTakingPart (java.util.Set _groupsCoursesTakingPart) {
		this._GroupsSubjectsTakingPart = _groupsCoursesTakingPart;
	}
	
	/**
	 * @deprecated
	 */
	public void addGroupCourseTakingPart (Object obj) {
		if (null == this._GroupsSubjectsTakingPart) this._GroupsSubjectsTakingPart = new java.util.HashSet();
		this._GroupsSubjectsTakingPart.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseSubject)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseSubject mObj = (fr.umlv.smoreau.beontime.model.base.BaseSubject) obj;
			if (null == this.getIdSubject() || null == mObj.getIdSubject()) return false;
			else return (this.getIdSubject().equals(mObj.getIdSubject()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdSubject()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdSubject().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}