package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Type_indisponibilite table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Type_indisponibilite"
 */
public abstract class BaseTypeUnavailability  implements Serializable {

	public static String PROP_NOM_TYPE_INDISPONIBILITE = "NomTypeIndisponibilite";
	public static String PROP_ID_TYPE_INDISPONIBILITE = "IdTypeIndisponibilite";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idTypeIndisponibilite;

	// fields
	private java.lang.String _nomTypeIndisponibilite;

	// collections
	private java.util.Set _indisponibiliteSet;


	// constructors
	public BaseTypeUnavailability () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTypeUnavailability (java.lang.Long _idTypeIndisponibilite) {
		this.setIdTypeIndisponibilite(_idTypeIndisponibilite);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_type_indisponibilite"
     */
	public java.lang.Long getIdTypeIndisponibilite () {
		return _idTypeIndisponibilite;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idTypeIndisponibilite the new ID
	 */
	public void setIdTypeIndisponibilite (java.lang.Long _idTypeIndisponibilite) {
		this._idTypeIndisponibilite = _idTypeIndisponibilite;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom_type_indisponibilite
	 */
	public java.lang.String getNomTypeIndisponibilite () {
		return _nomTypeIndisponibilite;
	}

	/**
	 * Set the value related to the column: Nom_type_indisponibilite
	 * @param _nomTypeIndisponibilite the Nom_type_indisponibilite value
	 */
	public void setNomTypeIndisponibilite (java.lang.String _nomTypeIndisponibilite) {
		this._nomTypeIndisponibilite = _nomTypeIndisponibilite;
	}


	/**
	 * Return the value associated with the column: IndisponibiliteSet
	 */
	public java.util.Set getIndisponibiliteSet () {
		return this._indisponibiliteSet;
	}

	/**
	 * Set the value related to the column: IndisponibiliteSet
	 * @param _indisponibiliteSet the IndisponibiliteSet value
	 */
	public void setIndisponibiliteSet (java.util.Set _indisponibiliteSet) {
		this._indisponibiliteSet = _indisponibiliteSet;
	}
	
	public void addToIndisponibiliteSet (Object obj) {
		if (null == this._indisponibiliteSet) this._indisponibiliteSet = new java.util.HashSet();
		this._indisponibiliteSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseTypeUnavailability)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseTypeUnavailability mObj = (fr.umlv.smoreau.beontime.model.base.BaseTypeUnavailability) obj;
			if (null == this.getIdTypeIndisponibilite() || null == mObj.getIdTypeIndisponibilite()) return false;
			else return (this.getIdTypeIndisponibilite().equals(mObj.getIdTypeIndisponibilite()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdTypeIndisponibilite()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdTypeIndisponibilite().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}