package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Type_indisponibilite table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Type_indisponibilite"
 */
public abstract class BaseUnavailabilityType  implements Serializable {

	public static String PROP_NOM_TYPE_INDISPONIBILITE = "NameUnavailabilityType";
	public static String PROP_ID_TYPE_INDISPONIBILITE = "IdUnavailabilityType";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idUnavailabilityType;

	// fields
	private java.lang.String _nameUnavailabilityType;

	// collections
	private java.util.Set _unavailabilities;


	// constructors
	public BaseUnavailabilityType () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUnavailabilityType (java.lang.Long _idUnavailabilityType) {
		this.setIdUnavailabilityType(_idUnavailabilityType);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_type_indisponibilite"
     */
	public java.lang.Long getIdUnavailabilityType () {
		return _idUnavailabilityType;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idUnavailabilityType the new ID
	 */
	public void setIdUnavailabilityType (java.lang.Long _idUnavailabilityType) {
		this._idUnavailabilityType = _idUnavailabilityType;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom_type_indisponibilite
	 */
	public java.lang.String getNameUnavailabilityType () {
		return _nameUnavailabilityType;
	}

	/**
	 * Set the value related to the column: Nom_type_indisponibilite
	 * @param _nameUnavailabilityType the Nom_type_indisponibilite value
	 */
	public void setNameUnavailabilityType (java.lang.String _nameUnavailabilityType) {
		this._nameUnavailabilityType = _nameUnavailabilityType;
	}


	/**
	 * Return the value associated with the column: IndisponibiliteSet
	 */
	public java.util.Set getUnavailabilities () {
		return this._unavailabilities;
	}

	/**
	 * Set the value related to the column: IndisponibiliteSet
	 * @param _unavailabilities the IndisponibiliteSet value
	 */
	public void setUnavailabilities (java.util.Set _unavailabilities) {
		this._unavailabilities = _unavailabilities;
	}
	
	public void addUnavailability (Object obj) {
		if (null == this._unavailabilities) this._unavailabilities = new java.util.HashSet();
		this._unavailabilities.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseUnavailabilityType)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseUnavailabilityType mObj = (fr.umlv.smoreau.beontime.model.base.BaseUnavailabilityType) obj;
			if (null == this.getIdUnavailabilityType() || null == mObj.getIdUnavailabilityType()) return false;
			else return (this.getIdUnavailabilityType().equals(mObj.getIdUnavailabilityType()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdUnavailabilityType()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdUnavailabilityType().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}