package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the groupe table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="groupe"
 */
public abstract class BaseGroup  implements Serializable {

	public static String PROP_ID_GROUPE = "IdGroup";
	public static String PROP_ID_FORMATION = "IdFormation";
	public static String PROP_INTITULE = "Heading";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idGroup;

	// fields
	private java.lang.Long _idFormation;
	private java.lang.String _heading;

	// collections
	private java.util.Set _subjectsCoursesTakePart;
	private java.util.Set _students;


	// constructors
	public BaseGroup () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseGroup (java.lang.Long _idGroup) {
		this.setIdGroup(_idGroup);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="id_groupe"
     */
	public java.lang.Long getIdGroup () {
		return _idGroup;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idGroup the new ID
	 */
	public void setIdGroup (java.lang.Long _idGroup) {
		this._idGroup = _idGroup;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: id_formation
	 */
	public java.lang.Long getIdFormation () {
		return _idFormation;
	}

	/**
	 * Set the value related to the column: id_formation
	 * @param _idFormation the id_formation value
	 */
	public void setIdFormation (java.lang.Long _idFormation) {
		this._idFormation = _idFormation;
	}


	/**
	 * Return the value associated with the column: Intitule
	 */
	public java.lang.String getHeading () {
		return _heading;
	}

	/**
	 * Set the value related to the column: Intitule
	 * @param _heading the Intitule value
	 */
	public void setHeading (java.lang.String _heading) {
		this._heading = _heading;
	}


	/**
	 * Return the value associated with the column: ParticipeGroupeMatiereCoursSet
	 */
	public java.util.Set getSubjectsCoursesTakePart () {
		return this._subjectsCoursesTakePart;
	}

	/**
	 * Set the value related to the column: ParticipeGroupeMatiereCoursSet
	 * @param _subjectsCoursesTakePart the ParticipeGroupeMatiereCoursSet value
	 */
	public void setSubjectsCoursesTakePart (java.util.Set _subjectsCoursesTakePart) {
		this._subjectsCoursesTakePart = _subjectsCoursesTakePart;
	}
	
	public void addSubjectCourseTakePart (Object obj) {
		if (null == this._subjectsCoursesTakePart) this._subjectsCoursesTakePart = new java.util.HashSet();
		this._subjectsCoursesTakePart.add(obj);
	}
	
	/**
	 * Return the value associated with the column: StudentSet
	 */
	public java.util.Set getStudents () {
		return this._students;
	}

	/**
	 * Set the value related to the column: StudentSet
	 * @param _students the StudentSet value
	 */
	public void setStudents (java.util.Set _students) {
		this._students = _students;
	}
	
	public void addStudent (Object obj) {
		if (null == this._students) this._students = new java.util.HashSet();
		this._students.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseGroup)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseGroup mObj = (fr.umlv.smoreau.beontime.model.base.BaseGroup) obj;
			if (null == this.getIdGroup() || null == mObj.getIdGroup()) return false;
			else return (this.getIdGroup().equals(mObj.getIdGroup()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdGroup()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdGroup().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}