package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;

import fr.umlv.smoreau.beontime.model.timetable.Course;
import fr.umlv.smoreau.beontime.model.user.User;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Est_Dirige_par_Cours_Enseignant table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Est_Dirige_par_Cours_Enseignant"
 */
public abstract class BaseIsDirectedByCourseTeacher  implements Serializable {



	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private User _idTeacher;
	private Course _idCourse;


	// constructors
	public BaseIsDirectedByCourseTeacher () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseIsDirectedByCourseTeacher (
		User _idTeacher,
		Course _idCourse) {

		this.setIdTeacher(_idTeacher);
		this.setIdCourse(_idCourse);
		initialize();
	}

	protected void initialize () {}



	/**
     * @hibernate.property
     *  column=ID_enseignant
	 * not-null=true
	 */
	public User getIdTeacher () {
		return this._idTeacher;
	}

	/**
	 * Set the value related to the column: ID_enseignant
	 * @param _idTeacher the ID_enseignant value
	 */
	public void setIdTeacher (User _idTeacher) {
		this._idTeacher = _idTeacher;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
     * @hibernate.property
     *  column=ID_cours
	 * not-null=true
	 */
	public Course getIdCourse () {
		return this._idCourse;
	}

	/**
	 * Set the value related to the column: ID_cours
	 * @param _idCourse the ID_cours value
	 */
	public void setIdCourse (Course _idCourse) {
		this._idCourse = _idCourse;
		this.hashCode = Integer.MIN_VALUE;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.association.IsDirectedByCourseTeacher)) return false;
		else {
			fr.umlv.smoreau.beontime.model.association.IsDirectedByCourseTeacher mObj = (fr.umlv.smoreau.beontime.model.association.IsDirectedByCourseTeacher) obj;
			if (null != this.getIdTeacher() && null != mObj.getIdTeacher()) {
				if (!this.getIdTeacher().equals(mObj.getIdTeacher())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getIdCourse() && null != mObj.getIdCourse()) {
				if (!this.getIdCourse().equals(mObj.getIdCourse())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getIdTeacher()) {
				sb.append(this.getIdTeacher().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getIdCourse()) {
				sb.append(this.getIdCourse().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}