package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Appartient_Etudiant_Groupe table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Appartient_Etudiant_Groupe"
 */
public abstract class BaseAppartientEtudiantGroupe  extends fr.umlv.smoreau.beontime.model.Group  implements Serializable {

	public static String PROP_ID_GROUPE = "IdGroupe";
	public static String PROP_ID_ETUDIANT = "IdEtudiant";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idGroupe;

	// fields
	private java.lang.Long _idEtudiant;


	// constructors
	public BaseAppartientEtudiantGroupe () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAppartientEtudiantGroupe (java.lang.Long _idGroupe) {
		super(_idGroupe);
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAppartientEtudiantGroupe (
		java.lang.Long _idGroupe,
		java.lang.Long _idFormation) {

		super (
			_idGroupe,
			_idFormation);
	}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_groupe"
     */
	public java.lang.Long getIdGroupe () {
		return _idGroupe;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idGroupe the new ID
	 */
	public void setIdGroupe (java.lang.Long _idGroupe) {
		this._idGroupe = _idGroupe;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: ID_etudiant
	 */
	public java.lang.Long getIdEtudiant () {
		return _idEtudiant;
	}

	/**
	 * Set the value related to the column: ID_etudiant
	 * @param _idEtudiant the ID_etudiant value
	 */
	public void setIdEtudiant (java.lang.Long _idEtudiant) {
		this._idEtudiant = _idEtudiant;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseAppartientEtudiantGroupe)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseAppartientEtudiantGroupe mObj = (fr.umlv.smoreau.beontime.model.base.BaseAppartientEtudiantGroupe) obj;
			if (null == this.getIdGroupe() || null == mObj.getIdGroupe()) return false;
			else return (this.getIdGroupe().equals(mObj.getIdGroupe()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdGroupe()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdGroupe().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}