package fr.umlv.smoreau.beontime.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Materiel table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Materiel"
 */
public abstract class BaseMaterial  implements Serializable {

	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_NOM = "Name";
	public static String PROP_ID_MATERIEL = "IdMaterial";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idMaterial;

	// fields
	private java.lang.String _description;
	private java.lang.String _name;

	// collections
	private java.util.Set _courses;


	// constructors
	public BaseMaterial () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMaterial (java.lang.Long _idMaterial) {
		this.setIdMaterial(_idMaterial);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_materiel"
     */
	public java.lang.Long getIdMaterial () {
		return _idMaterial;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idMaterial the new ID
	 */
	public void setIdMaterial (java.lang.Long _idMaterial) {
		this._idMaterial = _idMaterial;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: Description
	 * @param _description the Description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _name the Nom value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: CoursSet
	 */
	public java.util.Set getCourses () {
		return this._courses;
	}

	/**
	 * Set the value related to the column: CoursSet
	 * @param _courses the CoursSet value
	 */
	public void setCourses (java.util.Set _courses) {
		this._courses = _courses;
	}
	
	public void addCourse (Object obj) {
		if (null == this._courses) this._courses = new java.util.HashSet();
		this._courses.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.base.BaseMaterial)) return false;
		else {
			fr.umlv.smoreau.beontime.model.base.BaseMaterial mObj = (fr.umlv.smoreau.beontime.model.base.BaseMaterial) obj;
			if (null == this.getIdMaterial() || null == mObj.getIdMaterial()) return false;
			else return (this.getIdMaterial().equals(mObj.getIdMaterial()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdMaterial()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdMaterial().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}