package fr.umlv.smoreau.beontime.base;

import java.io.Serializable;

import fr.umlv.smoreau.beontime.model.timetable.Course;
import fr.umlv.smoreau.beontime.model.user.Person;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Est_Dirige_par_Cours_Enseignant table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Est_Dirige_par_Cours_Enseignant"
 */
public abstract class BaseIsDirigeByCourseTeacher  implements Serializable {



	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private Person _idEnseignant;
	private Course _idCours;


	// constructors
	public BaseIsDirigeByCourseTeacher () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseIsDirigeByCourseTeacher (
		Person _idEnseignant,
		Course _idCours) {

		this.setIdTeacher(_idEnseignant);
		this.setIdCourse(_idCours);
		initialize();
	}

	protected void initialize () {}



	/**
     * @hibernate.property
     *  column=ID_enseignant
	 * not-null=true
	 */
	public Person getIdTeacher () {
		return this._idEnseignant;
	}

	/**
	 * Set the value related to the column: ID_enseignant
	 * @param _idEnseignant the ID_enseignant value
	 */
	public void setIdTeacher (Person _idEnseignant) {
		this._idEnseignant = _idEnseignant;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
     * @hibernate.property
     *  column=ID_cours
	 * not-null=true
	 */
	public Course getIdCourse () {
		return this._idCours;
	}

	/**
	 * Set the value related to the column: ID_cours
	 * @param _idCours the ID_cours value
	 */
	public void setIdCourse (Course _idCours) {
		this._idCours = _idCours;
		this.hashCode = Integer.MIN_VALUE;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.association.IsDirigeByCourseTeacher)) return false;
		else {
			fr.umlv.smoreau.beontime.model.association.IsDirigeByCourseTeacher mObj = (fr.umlv.smoreau.beontime.model.association.IsDirigeByCourseTeacher) obj;
			if (null != this.getIdTeacher() && null != mObj.getIdTeacher()) {
				if (!this.getIdTeacher().equals(mObj.getIdTeacher())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getIdCourse() && null != mObj.getIdCourse()) {
				if (!this.getIdCourse().equals(mObj.getIdCourse())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getIdTeacher()) {
				sb.append(this.getIdTeacher().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getIdCourse()) {
				sb.append(this.getIdCourse().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}