package fr.umlv.smoreau.beontime.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Personne table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Personne"
 */
public abstract class BasePerson  implements Serializable {

	public static String PROP_E_MAIL = "EMail";
	public static String PROP_NOM = "Nom";
	public static String PROP_NOM_BUREAU = "NomBureau";
	public static String PROP_TELEPHONE = "Telephone";
	public static String PROP_PRENOM = "Prenom";
	public static String PROP_ID_PERSONNE = "IdPersonne";
	public static String PROP_NOM_BATIMENT_BUREAU = "NomBatimentBureau";
	public static String PROP_TYPE_PERSONNE = "TypePersonne";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.String _idPersonne;

	// fields
	private java.lang.String _nom;
	private java.lang.String _telephone;
	private java.lang.String _prenom;
	private java.lang.String _nomBureau;
	private java.lang.String _nomBatimentBureau;
	private java.lang.String _eMail;
	private java.lang.String _typePersonne;

	// collections
	private java.util.Set _participeGroupeMatiereCoursSet;
	private java.util.Set _formationSetByIdEnseignant;
	private java.util.Set _formationSetByIdSecretaire;
	private java.util.Set _matiereSet;
	private java.util.Set _coursSet;


	// constructors
	public BasePerson () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePerson (java.lang.String _idPersonne) {
		this.setIdPersonne(_idPersonne);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BasePerson (
		java.lang.String _idPersonne,
		java.lang.String _typePersonne) {

		this.setIdPersonne(_idPersonne);
		this.setTypePersonne(_typePersonne);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_personne"
     */
	public java.lang.String getIdPersonne () {
		return _idPersonne;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idPersonne the new ID
	 */
	public void setIdPersonne (java.lang.String _idPersonne) {
		this._idPersonne = _idPersonne;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: Telephone
	 */
	public java.lang.String getTelephone () {
		return _telephone;
	}

	/**
	 * Set the value related to the column: Telephone
	 * @param _telephone the Telephone value
	 */
	public void setTelephone (java.lang.String _telephone) {
		this._telephone = _telephone;
	}


	/**
	 * Return the value associated with the column: Prenom
	 */
	public java.lang.String getPrenom () {
		return _prenom;
	}

	/**
	 * Set the value related to the column: Prenom
	 * @param _prenom the Prenom value
	 */
	public void setPrenom (java.lang.String _prenom) {
		this._prenom = _prenom;
	}


	/**
	 * Return the value associated with the column: Nom_bureau
	 */
	public java.lang.String getNomBureau () {
		return _nomBureau;
	}

	/**
	 * Set the value related to the column: Nom_bureau
	 * @param _nomBureau the Nom_bureau value
	 */
	public void setNomBureau (java.lang.String _nomBureau) {
		this._nomBureau = _nomBureau;
	}


	/**
	 * Return the value associated with the column: Nom_batiment_bureau
	 */
	public java.lang.String getNomBatimentBureau () {
		return _nomBatimentBureau;
	}

	/**
	 * Set the value related to the column: Nom_batiment_bureau
	 * @param _nomBatimentBureau the Nom_batiment_bureau value
	 */
	public void setNomBatimentBureau (java.lang.String _nomBatimentBureau) {
		this._nomBatimentBureau = _nomBatimentBureau;
	}


	/**
	 * Return the value associated with the column: E_mail
	 */
	public java.lang.String getEMail () {
		return _eMail;
	}

	/**
	 * Set the value related to the column: E_mail
	 * @param _eMail the E_mail value
	 */
	public void setEMail (java.lang.String _eMail) {
		this._eMail = _eMail;
	}


	/**
	 * Return the value associated with the column: type_personne
	 */
	public java.lang.String getTypePersonne () {
		return _typePersonne;
	}

	/**
	 * Set the value related to the column: type_personne
	 * @param _typePersonne the type_personne value
	 */
	public void setTypePersonne (java.lang.String _typePersonne) {
		this._typePersonne = _typePersonne;
	}


	/**
	 * Return the value associated with the column: ParticipeGroupeMatiereCoursSet
	 */
	public java.util.Set getParticipeGroupeMatiereCoursSet () {
		return this._participeGroupeMatiereCoursSet;
	}

	/**
	 * Set the value related to the column: ParticipeGroupeMatiereCoursSet
	 * @param _participeGroupeMatiereCoursSet the ParticipeGroupeMatiereCoursSet value
	 */
	public void setParticipeGroupeMatiereCoursSet (java.util.Set _participeGroupeMatiereCoursSet) {
		this._participeGroupeMatiereCoursSet = _participeGroupeMatiereCoursSet;
	}
	
	public void addToParticipeGroupeMatiereCoursSet (Object obj) {
		if (null == this._participeGroupeMatiereCoursSet) this._participeGroupeMatiereCoursSet = new java.util.HashSet();
		this._participeGroupeMatiereCoursSet.add(obj);
	}



	/**
	 * Return the value associated with the column: FormationSetByIdEnseignant
	 */
	public java.util.Set getFormationSetByIdEnseignant () {
		return this._formationSetByIdEnseignant;
	}

	/**
	 * Set the value related to the column: FormationSetByIdEnseignant
	 * @param _formationSetByIdEnseignant the FormationSetByIdEnseignant value
	 */
	public void setFormationSetByIdEnseignant (java.util.Set _formationSetByIdEnseignant) {
		this._formationSetByIdEnseignant = _formationSetByIdEnseignant;
	}
	
	public void addToFormationSetByIdEnseignant (Object obj) {
		if (null == this._formationSetByIdEnseignant) this._formationSetByIdEnseignant = new java.util.HashSet();
		this._formationSetByIdEnseignant.add(obj);
	}



	/**
	 * Return the value associated with the column: FormationSetByIdSecretaire
	 */
	public java.util.Set getFormationSetByIdSecretaire () {
		return this._formationSetByIdSecretaire;
	}

	/**
	 * Set the value related to the column: FormationSetByIdSecretaire
	 * @param _formationSetByIdSecretaire the FormationSetByIdSecretaire value
	 */
	public void setFormationSetByIdSecretaire (java.util.Set _formationSetByIdSecretaire) {
		this._formationSetByIdSecretaire = _formationSetByIdSecretaire;
	}
	
	public void addToFormationSetByIdSecretaire (Object obj) {
		if (null == this._formationSetByIdSecretaire) this._formationSetByIdSecretaire = new java.util.HashSet();
		this._formationSetByIdSecretaire.add(obj);
	}



	/**
	 * Return the value associated with the column: MatiereSet
	 */
	public java.util.Set getMatiereSet () {
		return this._matiereSet;
	}

	/**
	 * Set the value related to the column: MatiereSet
	 * @param _matiereSet the MatiereSet value
	 */
	public void setMatiereSet (java.util.Set _matiereSet) {
		this._matiereSet = _matiereSet;
	}
	
	public void addToMatiereSet (Object obj) {
		if (null == this._matiereSet) this._matiereSet = new java.util.HashSet();
		this._matiereSet.add(obj);
	}



	/**
	 * Return the value associated with the column: CoursSet
	 */
	public java.util.Set getCoursSet () {
		return this._coursSet;
	}

	/**
	 * Set the value related to the column: CoursSet
	 * @param _coursSet the CoursSet value
	 */
	public void setCoursSet (java.util.Set _coursSet) {
		this._coursSet = _coursSet;
	}
	
	public void addToCoursSet (Object obj) {
		if (null == this._coursSet) this._coursSet = new java.util.HashSet();
		this._coursSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.base.BasePerson)) return false;
		else {
			fr.umlv.smoreau.beontime.base.BasePerson mObj = (fr.umlv.smoreau.beontime.base.BasePerson) obj;
			if (null == this.getIdPersonne() || null == mObj.getIdPersonne()) return false;
			else return (this.getIdPersonne().equals(mObj.getIdPersonne()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdPersonne()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdPersonne().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}