package fr.umlv.smoreau.beontime.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Materiel table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Materiel"
 */
public abstract class BaseMaterial  implements Serializable {

	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_NOM = "Nom";
	public static String PROP_ID_MATERIEL = "IdMateriel";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idMateriel;

	// fields
	private java.lang.String _description;
	private java.lang.String _nom;

	// collections
	private java.util.Set _coursSet;


	// constructors
	public BaseMaterial () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMaterial (java.lang.Long _idMateriel) {
		this.setIdMateriel(_idMateriel);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_materiel"
     */
	public java.lang.Long getIdMateriel () {
		return _idMateriel;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idMateriel the new ID
	 */
	public void setIdMateriel (java.lang.Long _idMateriel) {
		this._idMateriel = _idMateriel;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: Description
	 * @param _description the Description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: CoursSet
	 */
	public java.util.Set getCoursSet () {
		return this._coursSet;
	}

	/**
	 * Set the value related to the column: CoursSet
	 * @param _coursSet the CoursSet value
	 */
	public void setCoursSet (java.util.Set _coursSet) {
		this._coursSet = _coursSet;
	}
	
	public void addToCoursSet (Object obj) {
		if (null == this._coursSet) this._coursSet = new java.util.HashSet();
		this._coursSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.base.BaseMaterial)) return false;
		else {
			fr.umlv.smoreau.beontime.base.BaseMaterial mObj = (fr.umlv.smoreau.beontime.base.BaseMaterial) obj;
			if (null == this.getIdMateriel() || null == mObj.getIdMateriel()) return false;
			else return (this.getIdMateriel().equals(mObj.getIdMateriel()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdMateriel()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdMateriel().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}