package fr.umlv.smoreau.beontime.base;

import java.io.Serializable;

import fr.umlv.smoreau.beontime.model.user.Person;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Formation table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Formation"
 */
public abstract class BaseFormation  implements Serializable {

	public static String PROP_ID_SECRETAIRE = "IdSecretaire";
	public static String PROP_ID_FORMATION = "IdFormation";
	public static String PROP_ID_ENSEIGNANT = "IdEnseignant";
	public static String PROP_INTITULE = "Intitule";
	public static String PROP__PG_DROPPED_4_ = "........pg.dropped.4........";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idFormation;

	// fields
	private java.lang.String _intitule;


	// many to one
	private Person _idSecretaire;
	private Person _idEnseignant;

	// collections
	private java.util.Set _groupeSet;
	private java.util.Set _matiereSet;


	// constructors
	public BaseFormation () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseFormation (java.lang.Long _idFormation) {
		this.setIdFormation(_idFormation);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseFormation (
		java.lang.Long _idFormation,
		Person _idSecretaire,
		Person _idEnseignant) {

		this.setIdFormation(_idFormation);
		this.setIdSecretaire(_idSecretaire);
		this.setIdTeacher(_idEnseignant);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_formation"
     */
	public java.lang.Long getIdFormation () {
		return _idFormation;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idFormation the new ID
	 */
	public void setIdFormation (java.lang.Long _idFormation) {
		this._idFormation = _idFormation;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Intitule
	 */
	public java.lang.String getIntitule () {
		return _intitule;
	}

	/**
	 * Set the value related to the column: Intitule
	 * @param _intitule the Intitule value
	 */
	public void setIntitule (java.lang.String _intitule) {
		this._intitule = _intitule;
	}


	/**
     * @hibernate.property
     *  column=ID_secretaire
	 * not-null=true
	 */
	public Person getIdSecretaire () {
		return this._idSecretaire;
	}

	/**
	 * Set the value related to the column: ID_secretaire
	 * @param _idSecretaire the ID_secretaire value
	 */
	public void setIdSecretaire (Person _idSecretaire) {
		this._idSecretaire = _idSecretaire;
	}


	/**
     * @hibernate.property
     *  column=ID_enseignant
	 * not-null=true
	 */
	public Person getIdTeacher () {
		return this._idEnseignant;
	}

	/**
	 * Set the value related to the column: ID_enseignant
	 * @param _idEnseignant the ID_enseignant value
	 */
	public void setIdTeacher (Person _idEnseignant) {
		this._idEnseignant = _idEnseignant;
	}


	/**
	 * Return the value associated with the column: GroupeSet
	 */
	public java.util.Set getGroupeSet () {
		return this._groupeSet;
	}

	/**
	 * Set the value related to the column: GroupeSet
	 * @param _groupeSet the GroupeSet value
	 */
	public void setGroupeSet (java.util.Set _groupeSet) {
		this._groupeSet = _groupeSet;
	}
	
	public void addToGroupeSet (Object obj) {
		if (null == this._groupeSet) this._groupeSet = new java.util.HashSet();
		this._groupeSet.add(obj);
	}



	/**
	 * Return the value associated with the column: MatiereSet
	 */
	public java.util.Set getMatiereSet () {
		return this._matiereSet;
	}

	/**
	 * Set the value related to the column: MatiereSet
	 * @param _matiereSet the MatiereSet value
	 */
	public void setMatiereSet (java.util.Set _matiereSet) {
		this._matiereSet = _matiereSet;
	}
	
	public void addToMatiereSet (Object obj) {
		if (null == this._matiereSet) this._matiereSet = new java.util.HashSet();
		this._matiereSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.base.BaseFormation)) return false;
		else {
			fr.umlv.smoreau.beontime.base.BaseFormation mObj = (fr.umlv.smoreau.beontime.base.BaseFormation) obj;
			if (null == this.getIdFormation() || null == mObj.getIdFormation()) return false;
			else return (this.getIdFormation().equals(mObj.getIdFormation()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdFormation()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdFormation().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}