package fr.umlv.smoreau.beontime.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Local table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Local"
 */
public abstract class BaseRoom  implements Serializable {

	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_NOM = "Nom";
	public static String PROP_ID_LOCAL = "IdLocal";
	public static String PROP_NOM_BATIMENT = "NomBatiment";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _idLocal;

	// fields
	private java.lang.String _nomBatiment;
	private java.lang.String _description;
	private java.lang.String _nom;

	// collections
	private java.util.Set _coursSet;


	// constructors
	public BaseRoom () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseRoom (java.lang.Long _idLocal) {
		this.setIdLocal(_idLocal);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="ID_local"
     */
	public java.lang.Long getIdLocal () {
		return _idLocal;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idLocal the new ID
	 */
	public void setIdLocal (java.lang.Long _idLocal) {
		this._idLocal = _idLocal;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom_batiment
	 */
	public java.lang.String getNomBatiment () {
		return _nomBatiment;
	}

	/**
	 * Set the value related to the column: Nom_batiment
	 * @param _nomBatiment the Nom_batiment value
	 */
	public void setNomBatiment (java.lang.String _nomBatiment) {
		this._nomBatiment = _nomBatiment;
	}


	/**
	 * Return the value associated with the column: Description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: Description
	 * @param _description the Description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: CoursSet
	 */
	public java.util.Set getCoursSet () {
		return this._coursSet;
	}

	/**
	 * Set the value related to the column: CoursSet
	 * @param _coursSet the CoursSet value
	 */
	public void setCoursSet (java.util.Set _coursSet) {
		this._coursSet = _coursSet;
	}
	
	public void addToCoursSet (Object obj) {
		if (null == this._coursSet) this._coursSet = new java.util.HashSet();
		this._coursSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.base.BaseRoom)) return false;
		else {
			fr.umlv.smoreau.beontime.base.BaseRoom mObj = (fr.umlv.smoreau.beontime.base.BaseRoom) obj;
			if (null == this.getIdLocal() || null == mObj.getIdLocal()) return false;
			else return (this.getIdLocal().equals(mObj.getIdLocal()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdLocal()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdLocal().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}