package fr.umlv.smoreau.beontime.base;

import java.io.Serializable;

import fr.umlv.smoreau.beontime.model.element.Material;
import fr.umlv.smoreau.beontime.model.timetable.Course;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Utilise_Cours_Materiel table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Utilise_Cours_Materiel"
 */
public abstract class BaseUseCourseMaterial  implements Serializable {



	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private Material _idMateriel;
	private Course _idCours;


	// constructors
	public BaseUseCourseMaterial () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUseCourseMaterial (
		Material _idMateriel,
		Course _idCours) {

		this.setIdMaterial(_idMateriel);
		this.setIdCourse(_idCours);
		initialize();
	}

	protected void initialize () {}



	/**
     * @hibernate.property
     *  column=ID_materiel
	 * not-null=true
	 */
	public Material getIdMaterial () {
		return this._idMateriel;
	}

	/**
	 * Set the value related to the column: ID_materiel
	 * @param _idMateriel the ID_materiel value
	 */
	public void setIdMaterial (Material _idMateriel) {
		this._idMateriel = _idMateriel;
		this.hashCode = Integer.MIN_VALUE;
	}

	/**
     * @hibernate.property
     *  column=ID_cours
	 * not-null=true
	 */
	public Course getIdCourse () {
		return this._idCours;
	}

	/**
	 * Set the value related to the column: ID_cours
	 * @param _idCours the ID_cours value
	 */
	public void setIdCourse (Course _idCours) {
		this._idCours = _idCours;
		this.hashCode = Integer.MIN_VALUE;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof fr.umlv.smoreau.beontime.model.association.UseCourseMaterial)) return false;
		else {
			fr.umlv.smoreau.beontime.model.association.UseCourseMaterial mObj = (fr.umlv.smoreau.beontime.model.association.UseCourseMaterial) obj;
			if (null != this.getIdMaterial() && null != mObj.getIdMaterial()) {
				if (!this.getIdMaterial().equals(mObj.getIdMaterial())) {
					return false;
				}
			}
			else {
				return false;
			}
			if (null != this.getIdCourse() && null != mObj.getIdCourse()) {
				if (!this.getIdCourse().equals(mObj.getIdCourse())) {
					return false;
				}
			}
			else {
				return false;
			}
			return true;
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			StringBuffer sb = new StringBuffer();
			if (null != this.getIdMaterial()) {
				sb.append(this.getIdMaterial().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			if (null != this.getIdCourse()) {
				sb.append(this.getIdCourse().hashCode());
				sb.append(":");
			}
			else {
				return super.hashCode();
			}
			this.hashCode = sb.toString().hashCode();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}